apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: abayomiganiy/converter
        envFrom:
          - configMapRef:
              name: converter-configmap
          - secretRef:
              name: converter-secret
              
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
